# -*- coding: utf-8 -*-
"""my-app.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xIle_h82p5sXrcPGig1hDSliHTkPqr8B

**bold text**
"""

pip install streamlit

pip install yfinance

import yfinance as yf
import streamlit as st
import pandas as pd

st.write("""
# Simple Stock Price App
## GOKUL RAJ

Shownn are the stock **closing price** and ***volume*** of Google!
""")

tickerSymbol = 'GOOGL'
tickerData = yf.Ticker(tickerSymbol)
tickerDf=tickerData.history(period='1d',start='2010-5-31', end='2020-5-31')

st.line_chart(tickerDf.Close)
st.line_chart(tickerDf.Volume)